### ISSUE TITLE
Course Progress Widget does not show correct unit progress or session/lesson

### ISSUE THREAD

**Issue by Supaiku** [woocommerce/sensei-course-progress#105]
### Steps to Reproduce (updated 2020-05-27 2:06pm EST)
1. Starta  course and compelte some of module 1's units 
2. complete only some units, then skip to Module 2
3. complete some of Module 2 units
4. See that the course bar is still showing Module 1's lessons/units and is stuck at the uncompleted unit
AND
5. even after going back to incomplete past units and completing them, the progress is not updated and the widget doens't catch up to the new module.

In other words:
1. Complete some Units,
2. Go to another Module, complete some units
3. Go somewhere else and try to complete units.
4. They do not display as completed correctly in the progress bar (but seem to complete correctly when referencing the Sensei Course Page)

See the mis-match here: https://pasteboard.co/Jalltsg.jpg

### What I Expected
It should:
1. Update units as completed, even if some have been done out of order
2. stay in the Lesson/Session you are in
3. Feature: add a notification when previous unit's haven't been completed.

### What Happened Instead
It stopped correctly updating once some units were skipped

### PHP / WordPress / Sensei Course Progress / Sensei LMS version
Sensei with WooCommerce Paid Courses: by Automattic – 3.0.1.2.0.1 – Installed version not tested with active version of WooCommerce 4.1.1
Sensei LMS Course Progress: by Automattic – 2.0.3
Sensei LMS: by Automattic – 3.0.1

### Browser / OS version
Firefox for sure, probably others

### Screenshot / Video
Minute ~2min and Minute ~9min+ in this video:
https://drive.google.com/file/d/1JCMf5sRf1CuNEcMT0ouA9V0rEtj2QEY9/view?usp=sharing

**Comment by donnapep** [comment]
I'm not able to reproduce this. In the screenshot below, I've completed Lesson 1 and Lesson 3 and the widget has updated accordingly:

![Screen Shot 2020-05-27 at 1 21 34 PM](https://user-images.githubusercontent.com/1190420/83052280-167ce100-a01d-11ea-821f-11e68d2a8798.jpg)

I'd recommend trying a new theme to see if that fixes it, or providing us with more information on your setup so that we can reliably reproduce. Thx!

**Comment by Supaiku** [comment]
Thanks for taking a look!

It's not clear that you're doing the steps to reproduce it... let me see if
I can clarify them.

Do you see what's happening on ours (in the video)?

There are a few things which seem different:
1. you have fewer units, so modules are all displayed

Also, the second piece of the issue is that then, when going back, the
units won't complete.

I'm not sure that your screenshot shows the Units or not, but ours doesn't
show all the modules, which is also confusing. (see video).

**Comment by Supaiku** [comment]
I updated the previous post.

See #5 in particular. There's a before and after. What happens when you complete lesson 2 in your example?

Also:
Yours shows multiple Modules, but ours only shows one module.
Screenshot: https://pasteboard.co/JaljXog.png
Furthermore, completing modules out of order doesn't result in the correst display on the Course Progress bar.

See in action here: https://www.sociocracyforall.org/lesson/post-meeting-2/
Course Signup: https://www.sociocracyforall.org/product/elc-express-learn-sociocracy-in-4-sessions-with-your-group/
Use coupon

**Comment by Supaiku** [comment]
could this be cache related?

**Comment by donnapep** [comment]
I see you've logged a ticket for this issue. To avoid duplicating effort, I think it's best to work with our Happiness Engineers to figure out how to reliably reproduce. Once we have that nailed down, they will open a new issue or re-open this one with steps to reproduce. Thx.

**Comment by Supaiku** [comment]
In case anyone else has a similar issue, it was not a plug issue but a WPFC setting issue.

Turning off widget caching (duh *smacks forehead*) did the trick: 
https://www.wpfastestcache.com/premium/widget-cache-reduce-the-number-of-sql-queries/
