### ISSUE TITLE
Double encoding of ampersand on module titles

### ISSUE THREAD

**Issue by andyadams** [woocommerce/sensei-course-progress#26]
Hey there, I have a client site which has ampersands `&` in the module names. WordPress seems to store Taxonomy Term `name` fields as HTML-encoded. That means that the call to `htmlspecialchars` results in double-encoding of these characters:

https://github.com/woothemes/sensei-course-progress/blob/master/includes/class-sensei-course-progress-widget.php#L84

Perhaps this should use the `$double_encode` parameter to prevent double encodings?

http://php.net/manual/en/function.htmlspecialchars.php

**Comment by donnapep** [comment]
This is only an issue when the _Display all Modules_ setting is not selected.

**Comment by jom** [comment]
This was fixed in #38
