### ISSUE TITLE
Bullets in Canvas theme

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/sensei-course-progress#31]
It seems the latest Canvas update has added bullets to the course progress widget.

The following CSS should fix it:

```
.widget.widget_sensei_course_progress .course-progress-lessons li:before, .widget.widget_sensei_course_progress .course-progress-navigation li:before {
        content: none;
   		margin-right: 0;
}
```

560935-zd-woothemes

**Comment by jeromestoel** [comment]
Thanks, this helped. 
I have the same problem with the widget 'Woocommerce products'
Do you know if there is a same kind CSS fix for it?

**Comment by aheckler** [comment]
582158-zd-woothemes

**Comment by donnapep** [comment]
Closing as Canvas is a retired theme.
