### ISSUE TITLE
Widget does not work if lessons are not in a module

### ISSUE THREAD

**Issue by donnapep** [woocommerce/sensei-course-progress#43]
Lessons that are not part of a module do not show up in the course progress widget. If a course has no modules, the widget shows the course name and nothing else:

![screen shot 2018-03-05 at 5 12 22 am](https://user-images.githubusercontent.com/1190420/36969552-ce12b018-2033-11e8-8bee-4f5775c78e6a.jpg)

#### Steps to Reproduce
1. Create a course that has no modules and a few lessons.
2. Add the widget to a sidebar.
3. Notice that only the course name is displayed, but no lessons.

#### What I Expected
For a course with no modules, each lesson should be displayed as a link under an _Other Lessons_ subheading.

If some lessons are in modules and others are not, then the lessons that are not included inside a module should appear at the very end under an _Other Lessons_ subheading.

![screen shot 2018-03-05 at 5 22 08 am](https://user-images.githubusercontent.com/1190420/36970067-4795c9d8-2035-11e8-890e-e198f7c47285.jpg)

#### What Happened Instead
The widget didn't display any lessons.

**Comment by alexsanford** [comment]
@lkraav Yeah, this is probably related. My PR should fix it by doing exactly what you suggested, grouping under "Other Lessons". See https://github.com/woocommerce/sensei-course-progress/pull/50/files#diff-317e4dba4c4d384e54cf46538fc32ccfR247
