### ISSUE TITLE
Change how Sensei dependencies are checked

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/sensei-course-progress#56]
Originally reported here: 1376873-zen

The Sensei Course Progress widget was not showing under Appearance > Widgets , so couldn't be used. We tested for conflicts, deactivated everything except Sensei and the Course Progress widget as well as with and without WooCommerce installed in case was something to do with required dependencies https://github.com/woocommerce/sensei-course-progress/blob/master/sensei-course-progress.php for this to work, but we still had no luck and we were unable to replicate a my test site.

After further investigation by @jom  seems that dependencies are checked by validating specific directories, which made the extension to fail to load in this case as the Sensei plugin was installed in `plugins/woo-themes-sensei` instead of `plugins/woothemes-sensei`

This can be seen here: https://github.com/woocommerce/sensei-course-progress/blob/2ac98ab2c5a4118907b65cd8c6cfff40601d5549/woo-includes/class-woothemes-sensei-dependencies.php#L23

Maybe a better way to check this would be via class `class_exists()` instead ?

As a side note, after a first glance to other Sensei extensions code seems that the same dependency check happens as well but I didn't want to start to open issues on other repos until a direction is taken first here.

**Comment by lkraav** [comment]
Correct. Checking for specific directory names is a terrible idea, harking back to early WooCommerce days. This makes, for example, switching between parallel plugin feature branches an unnecessary headache.

Check for the main object access function `function_exists( 'Sensei' )` or the main class, instead.

**Comment by donnapep** [comment]
@iamgabrielma Would appreciate a quick test of this change as you are the OP. 🙂Testing instructions can be found in p6rkRX-XV-p2.
