### ISSUE TITLE
INPUT issue on checkout does not accept phone numbers

### ISSUE THREAD

**Issue by adorosermulher** [woocommerce/sensei-course-progress#58]
Hi,

In the fields my clients cant fill the phone number cause it always report a input issue or bug and doesnt allow the client to finish the check out.

I attached a print screen. We already try a diferent number, delete and write again, and nothing
Thank you 

![woo input](https://user-images.githubusercontent.com/44063402/46811954-a9470a00-cd6b-11e8-93d1-ebdafb5c2594.png)

**Comment by donnapep** [comment]
Hi,

That form is not part of Sensei Course Progress. Are you using WooCommerce? It looks like it may be a WooCommerce form. If so, the best place to get help is by opening [a ticket](https://woocommerce.com/my-account/create-a-ticket/).

Thx.
