### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by amroland** [woocommerce/sensei-course-progress#75]
You can find the Hungarian translation for Sensei Course Progress 2.0.0 beta:
[sensei-course-progress-hu_HU.zip](https://github.com/woocommerce/sensei-course-progress/files/2999300/sensei-course-progress-hu_HU.zip)

**Comment by donnapep** [comment]
Thanks @amroland! We've already released betas for Sensei and all of our extensions, so these will go in a subsequent release.

**Comment by donnapep** [comment]
Closed in #83.
