### ISSUE TITLE
DIVI doesn't support the formats of Sensei Course Progress

### ISSUE THREAD

**Issue by amroland** [woocommerce/sensei-course-progress#76]
Sensei Course Progress doesn't show its formats in DIVI in the sidebar widget.
Sidebar widget in Storefront:
![Képernyőfotó 2019-04-12 - 11 08 50](https://user-images.githubusercontent.com/39312392/56026171-e9377b80-5d13-11e9-883b-4c34777cc79f.png)

Sidebar widget in DIVI:
![Képernyőfotó 2019-04-12 - 11 06 04](https://user-images.githubusercontent.com/39312392/56026191-efc5f300-5d13-11e9-8d27-eca6219cb8de.png)

**Comment by donnapep** [comment]
Closing as this was fixed in #53 and will be released in version 2.0.0.
