### ISSUE TITLE
Can't activate license 

### ISSUE THREAD

**Issue by dericleeyy** [woocommerce/sensei-course-progress#99]
#### Steps to Reproduce
1. Go to https://woocommerce.com/products/sensei-course-progress/
2. Add it to your account
3. Go to your site WooCommerce > Extensions > Subscriptions
4. Download Course Progress from the link
5. Install and activate the plugin
6. Go back to the Subscriptions page

#### What I Expected
The subscription page should show that the plugin is installed and giving the option to activate

#### What Happened Instead
A download button is still shown.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/4032898/77730353-95fd2c80-703b-11ea-8bcf-a427796efcf5.png)

#### Context / Source
2811436-zen

**Comment by donnapep** [comment]
Closing as this isn't an issue with the plugin. See p6JqRr-2GX-p2 for details.
